### ISSUE TITLE
Default save location

### ISSUE THREAD

**Issue by markloe** [rnleach/IMETGeo#18] opened 2016-06-16 14:57 UTC
The default location to save an exported Placefile is /ProgramFiles/PFB/bin. Is it possible to have this the location where the shapefile was imported from? Or possibly a generic Directories folder?

**Comment by rnleach** [comment] 2016-06-16 16:17
I'm not sure of the correct way to find the user's home or documents directory, so I'll look into doing that.  Since I expect the typical use case to be to convert multiple sources (shapefiles, KML/KMZ, FileGeoDatabases) at a time to a single placefile, there is no obvious directory to choose for that.

I could add a check to see if there is only 1 source loaded, and if that is the cause default to that directory, otherwise try to find a 'Documents' or 'Home' directory of some sort.

**Comment by rnleach** [comment] 2016-07-31 10:47
Closed in win32 branch with 181b2b38d34a44e6de2805835f0558431f6cf486.

**Closed as completed by rnleach** 2016-07-31 10:47 UTC
Labels: enhancement
